:source-highlighter: highlight.js
:highlightjs-languages: rust
:github-icon: pass:[<svg class="icon"><use href="#github-icon"/></svg>]
= Fungible Token Standard

https://github.com/OpenZeppelin/stellar-contracts/tree/main/contracts/token/fungible[Source Code]

== Purpose

The Fungible Token Standard is a contract template designed to facilitate the creation and management of fungible tokens on the Stellar network.
It provides a flexible and secure framework for defining and managing token standards, enabling developers to create and manage tokens with ease.

== Extensions

We provide the below extensions to enhance the capabilities of the Fungible Token Standard.

=== - Mintable
https://github.com/OpenZeppelin/stellar-contracts/tree/main/contracts/token/fungible/src/extensions/mintable[Source Code]

==== Summary
The `FungibleMintable` trait extends the `FungibleToken` trait to provide the capability to mint tokens.

==== Events
* `mint_event` :  broadcasted to the network when the `mint()` function is invoked.

=== - Capped
https://github.com/OpenZeppelin/stellar-contracts/tree/main/contracts/token/fungible/src/extensions/capped[Source Code]

==== Summary
The `Capped` trait extends the `FungibleToken` trait to provide the capability to set a maximum supply for the token.

Note that the `Capped` trait is designed to be used in conjunction with the `Mintable` trait.

==== Events
There are no custom events associated with the `Capped` trait.

=== - Burnable
https://github.com/OpenZeppelin/stellar-contracts/tree/main/contracts/token/fungible/src/extensions/burnable[Source Code]

==== Summary
The `FungibleBurnable` trait extends the `FungibleToken` trait to provide the
capability to burn tokens.

To fully comply with the SEP-41 specification one have to implement the
this `FungibleBurnable` trait along with the `[FungibleToken]` trait.
SEP-41 mandates support for token burning to be considered compliant.

Excluding the `burn` functionality from the `[FungibleToken]` trait
is a deliberate design choice to accommodate flexibility and customization
for various smart contract use cases.

==== Events
* `burn_event`: broadcasted to the network when the `burn()` or `burn_from()` function is invoked.

=== - Metadata
https://github.com/OpenZeppelin/stellar-contracts/tree/main/contracts/token/fungible/src/extensions/metadata[Source Code]

==== Summary
Provides `setter` and `getter` methods for `symbol`, `name`, and `decimal` metadata information for your token.

==== Events
There are no custom events associated with the `Metadata` trait.
